#!/bin/bash

# ANSI escape codes for colors and reset
COLOR_WHITE='\e[1;37m'
COLOR_YELLOW='\e[1;33m'
COLOR_RESET='\e[0m'
BLINK='\e[5m'   # Blinking text

# Get terminal size
rows=$(tput lines)
cols=$(tput cols)

# Calculate center position
center_row=$((rows / 2))
center_col=$((cols / 2))

move_cursor_to_center() {
  echo -e "\e033[${center_row};${center_col}H"
}

for i in {1..10}; then
  move_cursor_to_center
  if (( i % 2 == 0 )); then
    echo -e "${BLINK}${COLOR_WHITE}This is blinking text!${COLOR_RESET}"
  else
    echo -e "${BLINK}${COLOR_YELLOW}This is blinking text!${COLOR_RESET}"
  fi
  tput cuu1
done
