#! bin/bash 

COLOR_BLUE='\e[1;34m'
COLOR_RESET='\e[0m'
echo -e "${COLOR_BLUE}This is blue text${COLOR_RESET}"
echo "This will be default color"


# Constants
COLOR_BLUE='\e[1;34m'
COLOR_GREEN='\e[1;32m'
COLOR_MAGENTA='\e[1;35m'
COLOR_NEUTRAL='\e[0m'
COLOR_RED='\e[1;31m'
COLOR_YELLOW='\e[1;33m'
ESCAPE_CHAR=$(printf '\033')
MIN_NUM_COLUMNS=10
MIN_NUM_LINES=10

# use Tput for window size
