#!/bin/sh

# use simple while loop instead of jobs or blocking stuff
# stty uses for I/O interface, cancel cano mode, disable echo, set max time wait limit 2000 ms




stty -icanon -echo time 20 min 0

# Game loop
while true; do
  echo 'BEGIN'
  key=$(dd bs=1 count=1 2> /dev/null)

  if [ ! "$key" = '' ]; then
    echo "You pressed: $key"
  fi
  echo 'END'
done
